### ISSUE TITLE
Wrong interpretation - number of occurrences

### ISSUE THREAD

**Issue by xhuli** [ForbesLindesay/regexplained.co.uk#5]
Tested at http://regexper.com/ 

Consider the following expression: `^(?=\d{1,2}([-.,\/])\d{3,4}\1\d{4}$)$`
- for `d{1,2}` it says `'at most once'` instead of `'up to 2'`
- for `d{3,4}` it says `'2…3 times'` instead of `'3…4 times'`
- for `d{4}` it says `'3 times'` instead of `'4 times'`

**Comment by ForbesLindesay** [comment]
I'm not sure exactly when it was fixed, but this seems to work now
